server.port=8083
spring.application.name=bank-scoring-service

spring.datasource.url=jdbc:h2:mem:bankscoringdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

scoring.frequency-weight=1.0
scoring.recency-weight=1.0
scoring.time-weight=0.5

payee.service.url=${PAYEE_SERVICE_URL:http://localhost:8082}
